name: Build Windows Package
on:
  push:
    branches:
      - test_workflows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install nsis
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install
          .\vcpkg\vcpkg install sfml

      - name: Build DLL
        run: |
          cmake -B build
          cmake --build build

      - name: Prepare for NSIS
        run: |
          copy build\NomDeVotreDLL.dll chemin\attendu\pour\NSIS\

      - name: Build installer with NSIS
        run: |
          makensis ./scripts/build-windows-engine.nsi