  name: Build DEB Package

  on:
    push:
      branches:
        - main
        - test_workflows
    pull_request:

  jobs:
    build-deb:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential devscripts debhelper libsfml-dev

        - name: Prepare files for packaging
          run: |
            mkdir -p package-build/src
            mkdir -p package-build/debian/tmp/usr/lib/
            cp -r src/* package-build/src/
            cp copyright package-build/debian
            cmake -Bbuild
            cmake --build build
            cp build/libengine_lib.so package-build/debian/tmp/usr/lib/

        - name: Create DEB compat file
          run: |
            echo "13" > package-build/debian/compat

        - name: Create DEB changelog file
          run: |
            echo "libquantumvortex-engine (1.0-1) buster; urgency=low" > package-build/debian/changelog
            echo "" >> package-build/debian/changelog
            echo "  * Initial release." >> package-build/debian/changelog
            echo "" >> package-build/debian/changelog
            echo " -- Campagne <thibault.campagne@epitech.eu>  Fri, 05 Jan 2024 03:08:00 +0100" >> package-build/debian/changelog

        - name: Create DEB control file
          run: |
            echo "Source: libquantumvortex-engine" > package-build/debian/control
            echo "Maintainer: Campagne <thibault.campagne@epitech.eu>" >> package-build/debian/control
            echo "Section: devel" >> package-build/debian/control
            echo "Priority: required" >> package-build/debian/control
            echo "Standards-Version: 4.6.2.0" >> package-build/debian/control
            echo "" >> package-build/debian/control
            echo "Package: libquantumvortex-engine-1.0" >> package-build/debian/control
            echo "Architecture: any" >> package-build/debian/control
            echo "Depends: libsfml-dev (>= 2.5.1), debhelper (>= 13.0)" >> package-build/debian/control
            echo "Description: The QuantumVortex Engine library is a 2D game engine" >> package-build/debian/control
            echo " designed to empower game developers in creating captivating 2D video games." >> package-build/debian/control
            echo " It provides a comprehensive set of tools, features, and resources for 2D game" >> package-build/debian/control
            echo " development. With QuantumVortex Engine, creators can easily craft 2D games," >> package-build/debian/control
            echo " design visually appealing graphics, manage game physics, and deliver immersive" >> package-build/debian/control
            echo " gaming experiences within a two-dimensional world." >> package-build/debian/control

        - name: Create DEB rules file
          run: |
            echo '#!/usr/bin/make -f' > package-build/debian/rules
            echo "" >> package-build/debian/rules
            echo "%:" >> package-build/debian/rules
            echo -e "\tdh \$@" >> package-build/debian/rules
            chmod +x package-build/debian/rules

        - name: Create debian/source/format
          run: |
            mkdir -p package-build/debian/source
            echo "3.0 (quilt)" > package-build/debian/source/format

        - name: Prepare original source tarball
          run: |
            tar czvf ./libquantumvortex-engine_1.0.orig.tar.gz --exclude=package-build *

        - name: Build DEB package
          run: |
            cd package-build
            debuild -us -uc

        - name: Upload DEB package
          uses: actions/upload-artifact@v2
          with:
            name: deb-package
            path: ./libquantumvortex-engine_*.deb
