name: Build RPM Package
on:
  push:
    branches:
      - test_workflows
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo dnf update -y
          sudo dnf install -y SFML-devel rpm-build

      - name: Configure and Build RPM
        run: |
          cmake -Bbuild -DCPACK_VERBOSE=ON .
          cmake --build build
          cd build
          cpack
