  name: Build DEB Package

  on:
    push:
      branches:
        # - main
        - test_workflows
    # pull_request:

  jobs:
    build-deb:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential devscripts debhelper debmake

        - name: Install SFML 2.6.1 dependencies
          run: |
            sudo apt-get install -y libsfml-dev libopenal-dev libvorbis-dev libogg-dev libflac-dev libudev-dev libxrandr-dev libxcursor-dev
        - name: Install SFML 2.6.1
          run: |
            git clone https://github.com/SFML/SFML.git SFML
            cd SFML
            git checkout 2.6.1
            cmake -Bbuild
            sudo cmake --build build --target install
            echo "SFML 2.6.1 installed successfully"

        - name: Prepare files for packaging
          run: |
            cmake -Bbuild
            cmake --build build
            cd build
            cpack
            mv 'QuantumVortex Engine-1.0.0-Linux.tar.gz' ../quantumvortex-engine-1.0.0.tar.gz
            cd ..
            tar xf quantumvortex-engine-1.0.0.tar.gz
            mv 'QuantumVortex Engine-1.0.0-Linux' quantumvortex-engine-1.0.0
            cd quantumvortex-engine-1.0.0
            echo ""
            ls -l
            echo ""

        - name: Generate Debian template
          run: |
            cd quantumvortex-engine-1.0.0
            debmake
            echo ""
            ls
            echo ""

        - name: Modify Debian changelog file
          run: |
            cd quantumvortex-engine-1.0.0
            rm debian/changelog
            mv ../debian_files/changelog debian/changelog

        - name: Modify Debian control file
          run: |
            cd quantumvortex-engine-1.0.0
            rm debian/control
            mv ../debian_files/control debian/control

        - name: Modify Debian rules file
          run: |
            cd quantumvortex-engine-1.0.0
            rm debian/rules
            mv ../debian_files/rules debian/rules

        - name: Modify Debian copyright file
          run: |
            cd quantumvortex-engine-1.0.0
            rm debian/copyright
            mv ../debian_files/copyright debian/copyright

        - name: Build DEB package
          run: |
            cd quantumvortex-engine-1.0.0
            echo ""
            tree
            echo ""
            debuild

        - name: Check if DEB package was created
          run: |
            echo ""
            ls -la
            echo ""
            dpkg -c quantumvortex-engine_*.deb

        - name: Upload DEB package
          uses: actions/upload-artifact@v3
          with:
            name: deb-package
            path: ./quantumvortex-engine_*.deb
