name: Build RPM Package

on:
  push:
    branches:
      # - main
      - test_workflows
      # - Issue#2

jobs:
  build-fedora-38:
    runs-on: ubuntu-latest
    container: fedora:38

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and compilers for Fedora 38
        run: |
          sudo dnf update -y
          sudo dnf install -y rpm-build gcc gcc-c++ cmake mesa-libGL-devel

      - name: Configure and Build RPM on Fedora 38
        run: |
          cmake -Bbuild -DCPACK_VERBOSE=ON
          cmake --build build
          cd build
          cpack
          mv *.rpm "quantumvortex-engine-fedora38.rpm"

      - name: Find RPM file for Fedora 38
        run: |
          echo "rpm_file=build/quantumvortex-engine-fedora38.rpm" >> $GITHUB_ENV

      - name: Upload RPM package for Fedora 38
        uses: actions/upload-artifact@v3
        with:
          name: rpm-package-fedora-38
          path: ${{ env.rpm_file }}

  build-fedora-latest:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and compilers for Fedora Latest
        run: |
          sudo dnf update -y
          sudo dnf install -y rpm-build gcc gcc-c++ cmake mesa-libGL-devel

      - name: Configure and Build RPM on Fedora Latest
        run: |
          cmake -Bbuild -DCPACK_VERBOSE=ON
          cmake --build build
          cd build
          cpack
          mv *.rpm "quantumvortex-engine-fedora-latest.rpm"

      - name: Find RPM file for Fedora Latest
        run: |
          echo "rpm_file=build/quantumvortex-engine-fedora-latest.rpm" >> $GITHUB_ENV

      - name: Upload RPM package for Fedora Latest
        uses: actions/upload-artifact@v3
        with:
          name: rpm-package-fedora-latest
          path: ${{ env.rpm_file }}
